name: 'LINE Notify'
description: 'LINE Notify for GitHub Actions'
inputs:
  my_url: ${{ secrets.MY_URL }}
  access_token:
    description: 'LINE Access Token'
    required: true
  message:
    description: 'Message'
    required: true
runs:
  using: 'node12'
  main: 'index.js'
branding:
  icon: 'message-circle'
  color: 'green'